apiVersion: v1
kind: Secret
metadata:
  name: indexer-secrets
  namespace: default
type: Opaque
stringData:
  graph-tenant-id: "your-tenant-id-here"
  graph-client-id: "your-client-id-here"
  graph-client-secret: "your-client-secret-here"
  openai-api-key: "sk-your-api-key-here"
  db-connection-string: "Host=postgres;Port=5432;Database=vectors;Username=indexer;Password=your-password;MinPoolSize=1;MaxPoolSize=3"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: docduck-indexer
  namespace: default
spec:
  # Run every 6 hours
  schedule: "0 */6 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: docduck-indexer
        spec:
          restartPolicy: OnFailure
          containers:
          - name: indexer
            image: your-registry/docduck-indexer:latest
            imagePullPolicy: Always
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            env:
            - name: GRAPH_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: graph-tenant-id
            - name: GRAPH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: graph-client-id
            - name: GRAPH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: graph-client-secret
            - name: GRAPH_DRIVE_ID
              value: "your-drive-id-here"
            - name: GRAPH_FOLDER_PATH
              value: "/Shared Documents/Docs"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: openai-api-key
            - name: OPENAI_BASE_URL
              value: "https://api.openai.com/v1"
            - name: OPENAI_EMBED_MODEL
              value: "text-embedding-3-small"
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: indexer-secrets
                  key: db-connection-string
            - name: CHUNK_SIZE
              value: "1000"
            - name: CHUNK_OVERLAP
              value: "200"
            - name: BATCH_SIZE
              value: "16"
