namespace Api.Services.Agents.Models;

/// <summary>
/// Search plan generated by the query planner agent.
/// </summary>
public sealed record SearchPlan(
    string OriginalQuery,
    List<string> Keywords,
    string Phrase,
    string? DocType,
    string? Language,
    string LookingFor
);
