{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docduck.secretName" . }}
  labels:
    {{- include "docduck.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ default "Opaque" .Values.secrets.type }}
stringData:
  {{- range $k, $v := .Values.secrets.stringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}

{{- range .Values.secrets.extra }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "docduck.labels" $ | nindent 4 }}
type: {{ default "Opaque" .type }}
{{- if .stringData }}
stringData:
  {{- range $k, $v := .stringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- if .data }}
data:
  {{- range $k, $v := .data }}
  {{ $k }}: {{ $v }}
  {{- end }}
{{- end }}
{{- end }}

{{- if .Values.config.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docduck.configName" . }}
  labels:
    {{- include "docduck.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}

{{- if and .Values.indexer.enabled .Values.indexer.config.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docduck.fullname" . }}-indexer-config
  labels:
    {{- include "docduck.labels" . | nindent 4 }}
data:
  appsettings.yaml: |
    # Generated by Helm from structured values
    {{- $cfg := .Values.indexer.config -}}
    {{- if $cfg.openAi.enabled }}
    OpenAi:
      ApiKey: "${OPENAI_API_KEY}"
      BaseUrl: {{ $cfg.openAi.baseUrl | quote }}
      EmbedModel: {{ $cfg.openAi.embedModel | quote }}
      BatchSize: {{ $cfg.openAi.batchSize }}
    {{- end }}

    {{- if $cfg.database.enabled }}
    Database:
      ConnectionString: "${DB_CONNECTION_STRING}"
    {{- end }}

    {{- if $cfg.chunking.enabled }}
    Chunking:
      ChunkSize: {{ $cfg.chunking.chunkSize }}
      ChunkOverlap: {{ $cfg.chunking.chunkOverlap }}
      MaxFiles: {{ if $cfg.chunking.maxFiles }}{{ $cfg.chunking.maxFiles }}{{ else }}null{{ end }}
    {{- end }}

    Providers:
      {{- if $cfg.providers.oneDrive.enabled }}
      OneDrive:
        Enabled: true
        Name: {{ $cfg.providers.oneDrive.name | quote }}
        AuthMode: {{ $cfg.providers.oneDrive.authMode | quote }}
        AccountType: {{ $cfg.providers.oneDrive.accountType | quote }}
        TenantId: "${{ $cfg.providers.oneDrive.tenantIdRef }}"
        ClientId: "${{ $cfg.providers.oneDrive.clientIdRef }}"
        ClientSecret: "${{ $cfg.providers.oneDrive.clientSecretRef }}"
        SiteId: "${{ $cfg.providers.oneDrive.siteIdRef }}"
        DriveId: "${{ $cfg.providers.oneDrive.driveIdRef }}"
        FolderPath: {{ $cfg.providers.oneDrive.folderPath | quote }}
        FileExtensions: {{ toYaml $cfg.providers.oneDrive.fileExtensions | nindent 8 | trim }}
      {{- else }}
      OneDrive:
        Enabled: false
      {{- end }}
      {{- if $cfg.providers.local.enabled }}
      Local:
        Enabled: true
        Name: {{ $cfg.providers.local.name | quote }}
        RootPath: {{ $cfg.providers.local.rootPath | quote }}
        Recursive: {{ $cfg.providers.local.recursive }}
        FileExtensions: {{ toYaml $cfg.providers.local.fileExtensions | nindent 8 | trim }}
        ExcludePatterns: {{ toYaml $cfg.providers.local.excludePatterns | nindent 8 | trim }}
      {{- else }}
      Local:
        Enabled: false
      {{- end }}
      {{- if $cfg.providers.s3.enabled }}
      S3:
        Enabled: true
        Name: {{ $cfg.providers.s3.name | quote }}
        BucketName: "${{ $cfg.providers.s3.bucketNameRef }}"
        Prefix: {{ $cfg.providers.s3.prefix | quote }}
        Region: {{ $cfg.providers.s3.region | quote }}
        UseInstanceProfile: {{ $cfg.providers.s3.useInstanceProfile }}
        FileExtensions: {{ toYaml $cfg.providers.s3.fileExtensions | nindent 8 | trim }}
      {{- else }}
      S3:
        Enabled: false
      {{- end }}

    {{- if $cfg.extraYaml }}
{{ $cfg.extraYaml | indent 4 }}
    {{- end }}
{{- end }}
