{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docduck.fullname" . }}-web
  labels:
    {{- include "docduck.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  revisionHistoryLimit: {{ .Values.web.revisionHistoryLimit }}
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "docduck.name" . }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "docduck.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ if .Values.web.serviceAccount.create }}{{ default (printf "%s-web" (include "docduck.fullname" .)) .Values.web.serviceAccount.name }}{{ else }}{{ .Values.web.serviceAccount.name }}{{ end }}
      containers:
        - name: web
          image: {{ include "docduck.componentImage" (dict "Values" .Values "component" .Values.web "Chart" .Chart "Release" .Release ) }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.targetPort }}
              protocol: TCP
          env:
            {{- range $k, $v := .Values.web.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- with .Values.web.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- range .Values.web.secretEnvs }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .key }}
            {{- end }}
          {{- with .Values.web.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
            {{- range .Values.web.envFromSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
