name: Release Helm Chart

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Chart version to release (e.g. 0.2.0)"
        required: true
      appVersion:
        description: "App version (image tag) to reference (e.g. 0.2.0)"
        required: true

permissions:
  contents: write
  packages: write

env:
  CHART_DIR: helm/docduck
  REGISTRY: ghcr.io
  OWNER: abrahamberg
  CHART_REPO: ghcr.io/abrahamberg/charts

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate semver
        run: |
          if ! echo "${{ github.event.inputs.version }}" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+'; then
            echo "Version must be semver without leading v (e.g. 0.3.1)" >&2
            exit 1
          fi
      - name: Update chart metadata
        run: |
          ver='${{ github.event.inputs.version }}'
          app='${{ github.event.inputs.appVersion }}'
          sed -i "s/^version: .*/version: ${ver}/" ${CHART_DIR}/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"${app}\"/" ${CHART_DIR}/Chart.yaml
          # update default image tags to appVersion
          sed -i "0,/repository: abrahamberg\/docduck\/api/{/tag: \".*\"/s//tag: \"${app}\"/}" ${CHART_DIR}/values.yaml
          sed -i "0,/repository: abrahamberg\/docduck\/web/{/tag: \".*\"/s//tag: \"${app}\"/}" ${CHART_DIR}/values.yaml
          sed -i "0,/repository: abrahamberg\/docduck\/indexer/{/tag: \".*\"/s//tag: \"${app}\"/}" ${CHART_DIR}/values.yaml
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add ${CHART_DIR}/Chart.yaml ${CHART_DIR}/values.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 0; fi
          git commit -m "release(chart): ${GITHUB_EVENT_INPUTS_VERSION} (app ${GITHUB_EVENT_INPUTS_APPVERSION})" || true
          git push || true
      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Package chart
        run: |
          mkdir -p dist
          helm package ${CHART_DIR} --destination dist
          ls -l dist
      - name: Push chart
        run: |
          chartFile=$(ls dist/docduck-${{ github.event.inputs.version }}.tgz)
          helm push ${chartFile} oci://ghcr.io/${{ env.OWNER }}/charts
      - name: Summary
        run: |
          echo "Released chart version ${{ github.event.inputs.version }} with appVersion ${{ github.event.inputs.appVersion }}" >> $GITHUB_STEP_SUMMARY
          echo "Pull: helm pull oci://ghcr.io/${{ env.OWNER }}/charts/docduck --version ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
